truncate table gsnmobile.ad_roas_kochava_phoenix_ods;

insert /*+ direct,LABEL ('airflow-ua-ua_master_main_dag.phoenix_subdag-t_update_ad_roas_kochava_phoenix')*/ into gsnmobile.ad_roas_kochava_phoenix_ods
SELECT platform,
       install_day,
       app_name,
       campaign_name,
       campaign_id,
       site_id,
       network_name,
       creative,
       country_code,
       request_campaign_id,
       request_adgroup,
       request_keyword,
       request_matchtype,
       model,
       device,
       first_ww_reg is not null as ww_registered,
       COUNT(DISTINCT idfv) AS installs,
       SUM(todate_bookings) AS todate_bookings,
       SUM(payer) AS todate_payers,
       SUM(day1_bookings) AS day1_bookings,
       SUM(day2_bookings) AS day2_bookings,
       SUM(day3_bookings) AS day3_bookings,
       SUM(day7_bookings) AS day7_bookings,
       SUM(day14_bookings) AS day14_bookings,
       SUM(day30_bookings) AS day30_bookings,
       SUM(day60_bookings) AS day60_bookings,
       SUM(day90_bookings) AS day90_bookings,
       SUM(day180_bookings) AS day180_bookings,
       SUM(day360_bookings) AS day360_bookings,
       SUM(day540_bookings) AS day540_bookings,
       SUM(day735_bookings) AS day735_bookings,
       SUM(day1_payer) AS day1_payers,
       SUM(day2_payer) AS day2_payers,
       SUM(day3_payer) AS day3_payers,
       SUM(day7_payer) AS day7_payers,
       SUM(day14_payer) AS day14_payers,
       SUM(day30_payer) AS day30_payers,
       SUM(day60_payer) AS day60_payers,
       SUM(day90_payer) AS day90_payers,
       SUM(day180_payer) AS day180_payers,
       SUM(day360_payer) AS day360_payers,
       SUM(day540_payer) AS day540_payers,
       SUM(day735_payer) AS day735_payers,
       SUM(todate_cef) AS todate_cef,
       SUM(cash_entrant) AS todate_cash_entrants,
       SUM(day1_cef) AS day1_cef,
       SUM(day2_cef) AS day2_cef,
       SUM(day3_cef) AS day3_cef,
       SUM(day7_cef) AS day7_cef,
       SUM(day14_cef) AS day14_cef,
       SUM(day30_cef) AS day30_cef,
       SUM(day60_cef) AS day60_cef,
       SUM(day90_cef) AS day90_cef,
       SUM(day180_cef) AS day180_cef,
       SUM(day360_cef) AS day360_cef,
       SUM(day540_cef) AS day540_cef,
       SUM(day735_cef) AS day735_cef,
       SUM(day1_cash_entrant) AS day1_cash_entrants,
       SUM(day2_cash_entrant) AS day2_cash_entrants,
       SUM(day3_cash_entrant) AS day3_cash_entrants,
       SUM(day7_cash_entrant) AS day7_cash_entrants,
       SUM(day14_cash_entrant) AS day14_cash_entrants,
       SUM(day30_cash_entrant) AS day30_cash_entrants,
       SUM(day60_cash_entrant) AS day60_cash_entrants,
       SUM(day90_cash_entrant) AS day90_cash_entrants,
       SUM(day180_cash_entrant) AS day180_cash_entrants,
       SUM(day360_cash_entrant) AS day360_cash_entrants,
       SUM(day540_cash_entrant) AS day540_cash_entrants,
       SUM(day735_cash_entrant) AS day735_cash_entrants,
       SUM(todate_deposits) AS todate_deposits,
       SUM(depositor) AS todate_depositors,
       SUM(todate_deposit_count) as todate_deposit_count,
       SUM(day1_deposits) AS day1_deposits,
       SUM(day2_deposits) AS day2_deposits,
       SUM(day3_deposits) AS day3_deposits,
       SUM(day7_deposits) AS day7_deposits,
       SUM(day14_deposits) AS day14_deposits,
       SUM(day30_deposits) AS day30_deposits,
       SUM(day60_deposits) AS day60_deposits,
       SUM(day90_deposits) AS day90_deposits,
       SUM(day180_deposits) AS day180_deposits,
       SUM(day360_deposits) AS day360_deposits,
       SUM(day540_deposits) AS day540_deposits,
       SUM(day735_deposits) AS day735_deposits,
       SUM(CASE WHEN day1_deposits > 0 then 1 else 0 end) AS day1_depositors,
       SUM(CASE WHEN day2_deposits > 0 then 1 else 0 end) AS day2_depositors,
       SUM(CASE WHEN day3_deposits > 0 then 1 else 0 end) AS day3_depositors,
       SUM(CASE WHEN day7_deposits > 0 then 1 else 0 end) AS day7_depositors,
       SUM(CASE WHEN day14_deposits > 0 then 1 else 0 end) AS day14_depositors,
       SUM(CASE WHEN day30_deposits > 0 then 1 else 0 end) AS day30_depositors,
       SUM(CASE WHEN day60_deposits > 0 then 1 else 0 end) AS day60_depositors,
       SUM(CASE WHEN day90_deposits > 0 then 1 else 0 end) AS day90_depositors,
       SUM(CASE WHEN day180_deposits > 0 then 1 else 0 end) AS day180_depositors,
       SUM(CASE WHEN day360_deposits > 0 then 1 else 0 end) AS day360_depositors,
       SUM(CASE WHEN day540_deposits > 0 then 1 else 0 end) AS day540_depositors,
       SUM(CASE WHEN day735_deposits > 0 then 1 else 0 end) AS day735_depositors,
       SUM(todate_withdrawals) AS todate_withdrawals,
       SUM(withdrawer) AS todate_withdrawers,
       SUM(todate_withdrawal_count) as todate_withdrawal_count,
       SUM(day1_withdrawals) AS day1_withdrawals,
       SUM(day2_withdrawals) AS day2_withdrawals,
       SUM(day3_withdrawals) AS day3_withdrawals,
       SUM(day7_withdrawals) AS day7_withdrawals,
       SUM(day14_withdrawals) AS day14_withdrawals,
       SUM(day30_withdrawals) AS day30_withdrawals,
       SUM(day60_withdrawals) AS day60_withdrawals,
       SUM(day90_withdrawals) AS day90_withdrawals,
       SUM(day180_withdrawals) AS day180_withdrawals,
       SUM(day360_withdrawals) AS day360_withdrawals,
       SUM(day540_withdrawals) AS day540_withdrawals,
       SUM(day735_withdrawals) AS day735_withdrawals,
       SUM(CASE WHEN day1_withdrawals > 0 then 1 else 0 end) AS day1_withdrawers,
       SUM(CASE WHEN day2_withdrawals > 0 then 1 else 0 end) AS day2_withdrawers,
       SUM(CASE WHEN day3_withdrawals > 0 then 1 else 0 end) AS day3_withdrawers,
       SUM(CASE WHEN day7_withdrawals > 0 then 1 else 0 end) AS day7_withdrawers,
       SUM(CASE WHEN day14_withdrawals > 0 then 1 else 0 end) AS day14_withdrawers,
       SUM(CASE WHEN day30_withdrawals > 0 then 1 else 0 end) AS day30_withdrawers,
       SUM(CASE WHEN day60_withdrawals > 0 then 1 else 0 end) AS day60_withdrawers,
       SUM(CASE WHEN day90_withdrawals > 0 then 1 else 0 end) AS day90_withdrawers,
       SUM(CASE WHEN day180_withdrawals > 0 then 1 else 0 end) AS day180_withdrawers,
       SUM(CASE WHEN day360_withdrawals > 0 then 1 else 0 end) AS day360_withdrawers,
       SUM(CASE WHEN day540_withdrawals > 0 then 1 else 0 end) AS day540_withdrawers,
       SUM(CASE WHEN day735_withdrawals > 0 then 1 else 0 end) AS day735_withdrawers,
       SUM(day1_retained) AS day1_retained,
       SUM(day2_retained) AS day2_retained,
       SUM(day3_retained) AS day3_retained,
       SUM(day7_retained) AS day7_retained,
       SUM(day14_retained) AS day14_retained,
       SUM(day30_retained) AS day30_retained,
       SUM(day60_retained) AS day60_retained,
       SUM(day90_retained) AS day90_retained,
       SUM(day180_retained) AS day180_retained,
       SUM(day360_retained) AS day360_retained,
       SUM(day540_retained) AS day540_retained,
       SUM(day540_retained) AS day735_retained,
       MAX(last_active_day) AS last_active_day --- added part of UA tableau SQL rewrite

FROM gsnmobile.kochava_device_summary_phoenix
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16;

truncate table gsnmobile.ad_roas_kochava_phoenix;
insert  /*+ direct,LABEL ('airflow-ua-ua_master_main_dag.phoenix_subdag-t_update_ad_roas_kochava_phoenix')*/ into  gsnmobile.ad_roas_kochava_phoenix select * from gsnmobile.ad_roas_kochava_phoenix_ods;
truncate table gsnmobile.ad_roas_kochava_phoenix_ods;

commit;
