SELECT  /*+ LABEL ('airflow-skill-worldwinner_gsncom_daily_imports-t_sftp_responsys_ww_pet_affinity_2')*/  CUSTOMER_ID,
        SOL_RUSH_SEC_GAME_AFF,
        SWAPIT_SEC_GAME_AFF,
        SPADES_SEC_GAME_AFF,
        LUXOR_SEC_GAME_AFF,
        BEJEWELED2_SEC_GAME_AFF,
        SCRABBLE_CUBES_SEC_GAME_AFF,
        SPIDER_SOL_SEC_GAME_AFF,
        CATCH_21_SEC_GAME_AFF,
        WOF_SEC_GAME_AFF,
        SUPER_PLINKO_SEC_GAME_AFF,
        BIG_MONEY_SEC_GAME_AFF,
        SOL_TRIPEAKS_SEC_GAME_AFF,
        TRIVIAL_PURSUIT_SEC_GAME_AFF,
        ABC_SEC_GAME_AFF,
        DYNOMITE_SEC_GAME_AFF,
        LIMITED_ENTRY_TOURN_AFF,
        SUPER_REWARDS_TOURN_AFF,
        FPUE_TOURN_AFF,
        PREMIUM_TOURN_AFF,
        PROGRESSIVE_RUSH_TOURN_AFF,
        PROGRESSIVE_TOURN_AFF,
        DESKTOP_AFF,
        MOWEB_AFF,
        APP_AFF
FROM airflow.snapshot_responsys_ww_pet_affinity
where ds =  '{{ ds }}'
EXCEPT
SELECT  CUSTOMER_ID,
        SOL_RUSH_SEC_GAME_AFF,
        SWAPIT_SEC_GAME_AFF,
        SPADES_SEC_GAME_AFF,
        LUXOR_SEC_GAME_AFF,
        BEJEWELED2_SEC_GAME_AFF,
        SCRABBLE_CUBES_SEC_GAME_AFF,
        SPIDER_SOL_SEC_GAME_AFF,
        CATCH_21_SEC_GAME_AFF,
        WOF_SEC_GAME_AFF,
        SUPER_PLINKO_SEC_GAME_AFF,
        BIG_MONEY_SEC_GAME_AFF,
        SOL_TRIPEAKS_SEC_GAME_AFF,
        TRIVIAL_PURSUIT_SEC_GAME_AFF,
        ABC_SEC_GAME_AFF,
        DYNOMITE_SEC_GAME_AFF,
        LIMITED_ENTRY_TOURN_AFF,
        SUPER_REWARDS_TOURN_AFF,
        FPUE_TOURN_AFF,
        PREMIUM_TOURN_AFF,
        PROGRESSIVE_RUSH_TOURN_AFF,
        PROGRESSIVE_TOURN_AFF,
        DESKTOP_AFF,
        MOWEB_AFF,
        APP_AFF
FROM airflow.snapshot_responsys_ww_pet_affinity
where ds =  '{{ yesterday_ds }}';