SELECT  /*+ LABEL ('airflow-skill-worldwinner_gsncom_daily_imports-t_sftp_responsys_ww_pet_affinity_1')*/  CUSTOMER_ID,
        APP_INSTALLED,
        SOL_RUSH_PRI_GAME_AFF,
        SWAPIT_PRI_GAME_AFF,
        SPADES_PRI_GAME_AFF,
        LUXOR_PRI_GAME_AFF,
        BEJEWELED2_PRI_GAME_AFF,
        SCRABBLE_CUBES_PRI_GAME_AFF,
        SPIDER_SOL_PRI_GAME_AFF,
        CATCH_21_PRI_GAME_AFF,
        WOF_PRI_GAME_AFF,
        SUPER_PLINKO_PRI_GAME_AFF,
        BIG_MONEY_PRI_GAME_AFF,
        SOL_TRIPEAKS_PRI_GAME_AFF,
        TRIVIAL_PURSUIT_PRI_GAME_AFF,
        ABC_PRI_GAME_AFF,
        DYNOMITE_PRI_GAME_AFF,
        NO_GAME_AFF,
        POP_PRI_GAME_AFF,
        TWODOTS_PRI_GAME_AFF,
        PACMAN_PRI_GAME_AFF,
        SWAP2_PRI_GAME_AFF,
        POP_SEC_GAME_AFF,
        TWODOTS_SEC_GAME_AFF,
        PACMAN_SEC_GAME_AFF,
        SWAP2_SEC_GAME_AFF
FROM airflow.snapshot_responsys_ww_pet_affinity
where ds =  '{{ ds }}'
EXCEPT
SELECT  CUSTOMER_ID,
        APP_INSTALLED,
        SOL_RUSH_PRI_GAME_AFF,
        SWAPIT_PRI_GAME_AFF,
        SPADES_PRI_GAME_AFF,
        LUXOR_PRI_GAME_AFF,
        BEJEWELED2_PRI_GAME_AFF,
        SCRABBLE_CUBES_PRI_GAME_AFF,
        SPIDER_SOL_PRI_GAME_AFF,
        CATCH_21_PRI_GAME_AFF,
        WOF_PRI_GAME_AFF,
        SUPER_PLINKO_PRI_GAME_AFF,
        BIG_MONEY_PRI_GAME_AFF,
        SOL_TRIPEAKS_PRI_GAME_AFF,
        TRIVIAL_PURSUIT_PRI_GAME_AFF,
        ABC_PRI_GAME_AFF,
        DYNOMITE_PRI_GAME_AFF,
        NO_GAME_AFF,
        POP_PRI_GAME_AFF,
        TWODOTS_PRI_GAME_AFF,
        PACMAN_PRI_GAME_AFF,
        SWAP2_PRI_GAME_AFF,
        POP_SEC_GAME_AFF,
        TWODOTS_SEC_GAME_AFF,
        PACMAN_SEC_GAME_AFF,
        SWAP2_SEC_GAME_AFF
FROM airflow.snapshot_responsys_ww_pet_affinity
where ds =  '{{ yesterday_ds }}';