DELETE /*+ direct ,LABEL ('airflow-all-ua_master_main_dag.ua_attribution_subdag-t_update_phoenix_ua')*/ FROM gsnmobile.kochava_device_summary
WHERE app_name = 'PHOENIX';

INSERT /*+direct, LABEL ('airflow-all-ua_master_main_dag.ua_attribution_subdag-t_update_phoenix_ua')*/
INTO gsnmobile.kochava_device_summary
SELECT
    idfv as synthetic_id,
    platform,
    install_timestamp,
    install_day,
    app_name,
    campaign_name,
    campaign_id,
    site_id,
    network_name,
    creative,
    null as adset_name,
    country_code,
    request_campaign_id,
    request_adgroup,
    request_keyword,
    request_matchtype,
    model,
    device,
    most_recent_os_version,
    first_payment_timestamp,
    last_payment_timestamp,
    first_active_day,
    last_active_day,
    first_ww_app_login,
    first_ww_reg,
    todate_bookings,
    payer,
    day1_bookings,
    day2_bookings,
    day3_bookings,
    day7_bookings,
    day14_bookings,
    day30_bookings,
    day60_bookings,
    day90_bookings,
    day180_bookings,
    day360_bookings,
    day540_bookings,
    day1_payer,
    day2_payer,
    day3_payer,
    day7_payer,
    day14_payer,
    day30_payer,
    day60_payer,
    day90_payer,
    day180_payer,
    day360_payer,
    day540_payer,
    day1_retained,
    day2_retained,
    day3_retained,
    day7_retained,
    day14_retained,
    day30_retained,
    day60_retained,
    day90_retained,
    day180_retained,
    day360_retained,
    day540_retained,
    null as app,
    null as last_open,
    null as day1_open,
    null as day2_open,
    null as day3_open,
    null as day7_open,
    null as day14_open,
    null as day30_open,
    null as day60_open,
    null as day90_open,
    null as day1_cumu_bookings,
    null as day2_cumu_bookings,
    null as day3_cumu_bookings,
    null as day7_cumu_bookings,
    null as day14_cumu_bookings,
    null as day30_cumu_bookings,
    null as day60_cumu_bookings,
    null as day90_cumu_bookings,
    null as total_bookings,
    null as day120_cumu_bookings,
    null as day150_cumu_bookings,
    null as day180_cumu_bookings,
    null as day210_cumu_bookings,
    null as day240_cumu_bookings,
    null as day270_cumu_bookings,
    null as day300_cumu_bookings,
    null as day330_cumu_bookings,
    null as day360_cumu_bookings,
    null as day540_cumu_bookings,
    null as day735_cumu_bookings,
    null as os_version,
    null as day180_open,
    null as day360_open,
    null as day540_open,
    null as install_date,
    kochava_install_timestamp,
    kochava_install_day,
    gsn_install_timestamp,
    gsn_install_day
FROM
    gsnmobile.kochava_device_summary_phoenix;

DELETE /*+ direct */ FROM gsnmobile.ad_roas_kochava
WHERE app_name = 'PHOENIX';

insert /*+direct*/ into gsnmobile.ad_roas_kochava
SELECT
    platform,
    install_day,
    app_name,
    campaign_name,
    campaign_id,
    site_id,
    network_name,
    creative,
    country_code,
    request_campaign_id,
    request_adgroup,
    request_keyword,
    request_matchtype,
    model,
    device,
    ww_registered,
    null as request_bundle_id,
    installs,
    todate_bookings,
    todate_payers,
    day1_bookings,
    day2_bookings,
    day3_bookings,
    day7_bookings,
    day14_bookings,
    day30_bookings,
    day60_bookings,
    day90_bookings,
    day180_bookings,
    day360_bookings,
    day540_bookings,
    day1_payers,
    day2_payers,
    day3_payers,
    day7_payers,
    day14_payers,
    day30_payers,
    day60_payers,
    day90_payers,
    day180_payers,
    day360_payers,
    day540_payers,
    day1_retained,
    day2_retained,
    day3_retained,
    day7_retained,
    day14_retained,
    day30_retained,
    day60_retained,
    day90_retained,
    day180_retained,
    day360_retained,
    day540_retained,
    last_active_day --- added part of UA tableau SQL rewrite
from
    gsnmobile.ad_roas_kochava_phoenix;

COMMIT;
